// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcoQy_DcaAiWyhkxJto9tBKbS-LE8u4pI',
    appId: '1:685520947066:web:0d74c5b930b51b0c2338c3',
    messagingSenderId: '685520947066',
    projectId: 'rocha-chat-app',
    authDomain: 'rocha-chat-app.firebaseapp.com',
    storageBucket: 'rocha-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhjlVLOiizYzKva1oHJYOdJ_I6Jx55Ys',
    appId: '1:685520947066:android:5df3cc3c065a66d12338c3',
    messagingSenderId: '685520947066',
    projectId: 'rocha-chat-app',
    storageBucket: 'rocha-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJb-g6CFxEeIkG9B-mEiJBzveYMyN1xg',
    appId: '1:685520947066:ios:6d329b251a97ee612338c3',
    messagingSenderId: '685520947066',
    projectId: 'rocha-chat-app',
    storageBucket: 'rocha-chat-app.appspot.com',
    iosClientId: '685520947066-hd4dtejtlobdhn6op2edjr5mc6om5ok3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rochaChatapp',
  );
}
