// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEWVypojZXcWHCB5jCkBC8YYV8qrrDNr4',
    appId: '1:45903894614:web:3bf59004f4493fe9f943f7',
    messagingSenderId: '45903894614',
    projectId: 'rochachat-app',
    authDomain: 'rochachat-app.firebaseapp.com',
    storageBucket: 'rochachat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdLA_M4hofWE9icnzWLDBUX5wLStkiMeQ',
    appId: '1:45903894614:android:faedb6575892de2af943f7',
    messagingSenderId: '45903894614',
    projectId: 'rochachat-app',
    storageBucket: 'rochachat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXmi44o1YF6oWbY4BxMuxi7sMqA8k6dAY',
    appId: '1:45903894614:ios:42f230c13fc5a4a2f943f7',
    messagingSenderId: '45903894614',
    projectId: 'rochachat-app',
    storageBucket: 'rochachat-app.appspot.com',
    iosClientId: '45903894614-or5avgr8c6jopp0kj97nguif3go1h2qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.rochaChatApp',
  );
}
